### ISSUE TITLE
Unclear order of presentation

### ISSUE THREAD

**Issue by JoFrhwld** [matthuntgardner/lvc_r#4]
The files

- `Doing_LVC_with_R.Rmd `
- `Getting Started.qmd`
- `Getting Your Data Into R.qmd`
- `Part1.qmd`

Are all rendered into pages. It's not clear which order you want them to appear in, or if theres any you want excluded?

**Comment by matthuntgardner** [comment]
Hi Joe, 
So, Doing LVC with R and Part 1 are no longer valid. 

It should go "Getting Started" then "Getting Your Data into R"

I'm not sure where/how to show the proper structure. Since we switched to quarter do I still put weight?

**Comment by JoFrhwld** [comment]
Ok, cool. Looks like you already got rid of them. 

We're not using weight anymore. Instead, the categories, subcategories, and the order of links to each page need to be written by hand in the main sites's _quart0.yml file. [Link to the line where that starts here](https://github.com/LingMethodsHub/LingMethodsHub.github.io/blob/6aa41ec75afb52581617b36e60c200a96403e8f9/_quarto.yml#L31). 

There's plusses and minuses to that I think. A minus is that it's more by-hand work. But some big plusses are that we don't need contributors to have any particular file structure, or have any required place holder files or anything. It also means we can reorganize the structure of the menu without changing any file organization or urls.

Maybe what would be a useful thing would be just to add a `README.md` file that just has a list of the order you intend the files to appear in.

**Comment by JoFrhwld** [comment]
New file naming convention closes this issue.
